<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kr.Carevo.UMR.Domain/Kr.Carevo.UMR.Domain.csproj" />
    <ProjectReference Include="../Kr.Carevo.UMR.Infrastructure/Kr.Carevo.UMR.Infrastructure.csproj" />
    <ProjectReference Include="../Kr.Carevo.UMR.Persistence/Kr.Carevo.UMR.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Feature/Application/" />
    <Folder Include="Feature/Application/Command/" />
    <Folder Include="Feature/Application/Command/Create/" />
    <Folder Include="Feature/Application/Query/" />
    <Folder Include="Feature/Application/Query/Fetch/" />
    <Folder Include="Mapper/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Asp.Versioning.Http" />
  </ItemGroup>

</Project>
