// <auto-generated />
using System;
using Kr.Carevo.UMR.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Kr.Carevo.UMR.Persistence.Migrations
{
    [DbContext(typeof(CarevoDbContext))]
    [Migration("20251230023502_UMRMigration_Initial_1_0_2_20251230133459")]
    partial class UMRMigration_Initial_1_0_2_20251230133459
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("carevo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("applicationhistoryseq", "carevo");

            modelBuilder.HasSequence<int>("applicationseq", "carevo");

            modelBuilder.HasSequence<int>("contactseq", "carevo");

            modelBuilder.HasSequence<int>("employmentseq", "carevo");

            modelBuilder.HasSequence<int>("projectseq", "carevo");

            modelBuilder.HasSequence<int>("skillseq", "carevo");

            modelBuilder.HasSequence<int>("streakseq", "carevo");

            modelBuilder.HasSequence<int>("userseq", "carevo");

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "applicationseq", "carevo");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CreatedBy");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar");

                    b.Property<string>("PersonalizedEmploymentData")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<uint>("VersionStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_applications_Id");

                    b.HasIndex("UserId");

                    b.ToTable("applications", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.ApplicationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "applicationhistoryseq", "carevo");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ApplicationId1")
                        .HasColumnType("integer");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar");

                    b.Property<string>("PreviousStatus")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("StatusChangedDate")
                        .HasColumnType("timestamp");

                    b.Property<long>("VersionStamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_application_status_history_Id");

                    b.HasIndex("ApplicationId1");

                    b.HasIndex("ApplicationId", "StatusChangedDate")
                        .HasDatabaseName("idx_app_history_appid_date");

                    b.ToTable("application_status_history", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Employment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "employmentseq", "carevo");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("Logo")
                        .HasColumnType("varchar");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("Url")
                        .HasColumnType("varchar");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<uint>("VersionStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_employments_Id");

                    b.HasIndex("UserId");

                    b.ToTable("employments", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "projectseq", "carevo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<int?>("EmploymentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<uint>("VersionStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_projects_Id");

                    b.HasIndex("EmploymentId");

                    b.HasIndex("UserId");

                    b.ToTable("projects", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.ProjectSkill", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("ProjectId", "SkillId")
                        .HasName("pk_project_skills");

                    b.HasIndex("SkillId");

                    b.ToTable("project_skills", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "skillseq", "carevo");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("effective_date");

                    b.Property<uint>("VersionStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_skills_id");

                    b.ToTable("skills", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Streak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "streakseq", "carevo");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<int>("ApplicationCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ConsecutiveDayCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<long>("VersionStamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_activity_streaks_Id");

                    b.HasIndex("UserId", "ActivityDate")
                        .IsUnique()
                        .HasDatabaseName("idx_activity_streaks_user_date");

                    b.HasIndex("UserId", "ConsecutiveDayCount")
                        .HasDatabaseName("idx_activity_streaks_user_consecutive");

                    b.ToTable("activity_streaks", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "userseq", "carevo");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("timestamp");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<uint>("VersionStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_Users_Id");

                    b.ToTable("users", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.HasKey("UserId", "SkillId")
                        .HasName("pk_user_skills");

                    b.HasIndex("SkillId");

                    b.ToTable("user_skills", "carevo");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Application", b =>
                {
                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.ApplicationStatusHistory", b =>
                {
                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_status_history_applications");

                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.Application", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("ApplicationId1");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Employment", b =>
                {
                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.User", "User")
                        .WithMany("Employments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employments_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Project", b =>
                {
                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.Employment", "Employment")
                        .WithMany("Projects")
                        .HasForeignKey("EmploymentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_projects_employments");

                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.User", "User")
                        .WithMany("IndividualProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_projects_users_individual");

                    b.Navigation("Employment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.ProjectSkill", b =>
                {
                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.Project", "Project")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_skills_projects");

                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_skills_skills");

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Streak", b =>
                {
                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.User", "User")
                        .WithMany("ActivityStreaks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_streaks_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.User", b =>
                {
                    b.OwnsOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.Address", "ResidentialAddress", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Address_City");

                            b1.Property<NpgsqlPoint?>("Coordinates")
                                .HasColumnType("point")
                                .HasColumnName("Address_Coordinates");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("Address_Line1");

                            b1.Property<string>("Line2")
                                .HasColumnType("varchar")
                                .HasColumnName("Address_Line2");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("varchar(20)")
                                .HasColumnName("Address_PostCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("Suburb")
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Address_Suburb");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "carevo");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("Kr.Carevo.UMR.Domain.Models.AggregateModels.Contact", "Contacts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseHiLo(b1.Property<int>("Id"), "contactseq", "carevo");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(500)")
                                .HasColumnName("value");

                            b1.Property<long>("VersionStamp")
                                .HasColumnType("bigint");

                            b1.Property<int>("user_id")
                                .HasColumnType("integer");

                            b1.HasKey("Id")
                                .HasName("pk_user_contacts_id");

                            b1.HasIndex("user_id");

                            b1.ToTable("user_contacts", "carevo");

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_user_contacts_users");
                        });

                    b.Navigation("Contacts");

                    b.Navigation("ResidentialAddress");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.UserSkill", b =>
                {
                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_skills_skills");

                    b.HasOne("Kr.Carevo.UMR.Domain.Models.AggregateModels.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_skills_users");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Application", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Employment", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Project", b =>
                {
                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.Skill", b =>
                {
                    b.Navigation("ProjectSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("Kr.Carevo.UMR.Domain.Models.AggregateModels.User", b =>
                {
                    b.Navigation("ActivityStreaks");

                    b.Navigation("Applications");

                    b.Navigation("Employments");

                    b.Navigation("IndividualProjects");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
